services:
  backend:
    build: ./backend
    ports:
      - 4000:4000
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/backend #links directories so updates happen on docker container instantly
      - /usr/src/backend/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    restart: unless-stopped

  mongo:
    image: mongo:7
    command: ["mongod", "--quiet"]
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
    depends_on:
     - mongo

  frontend:
    build: ./frontend
    working_dir: /usr/src/frontend
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # needed for hot reload inside Docker
    env_file:
      - ./backend/.env
    restart: unless-stopped

volumes:
  mongo_data: