services:
  backend:
    build: .
    ports:
      - 4000:4000
      - 9229:9229 # for debugging
    volumes:
     - .:/usr/src/backend #links directories so updates happen on docker container instantly
     - /usr/src/backend/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped